### ISSUE TITLE
Error:(97, 13) Failed to resolve: com.pluscubed:recycler-fast-scroll:0.2.1

### ISSUE THREAD

**Issue by codeversed** [plusCubed/recycler-fast-scroll#13]
Am I the only one that can't resolve this from jitpack? I know it is setup correctly and I also noticed that only if you login to jitpack, you can see the result here: https://jitpack.io/#com.pluscubed/recycler-fast-scroll

If you are not logged in to the site, it displays a token error. Seems like the repo is set to need some kind of token?

**Comment by afollestad** [comment]
@codeversed rather than following what's in the README, use this:

#### Repository

Add this in your root `build.gradle` file (**not** your module `build.gradle` file):

``` gradle
allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}
```

#### Dependency

Add this to your module's `build.gradle` file:

``` gradle
dependencies {
    ...
    compile('com.github.pluscubed:recycler-fast-scroll:0.2.1@aar') {
        transitive = true
    }
}
```

@plusCubed

**Comment by afollestad** [comment]
Putting it in the **root** `build.gradle` file is important. A few of my libraries (like Material Dialogs) caused a lot of people issues, JitPack.io told me to use Gradle code similar to the above. I've also had issues with using custom domains (e.g. `com.afollestad` vs. `com.github.afollestad`), so I'd recommend just using `com.github.pluscubed` here instead.

**Comment by codeversed** [comment]
Awesome, that worked!  Thanks @afollestad!
