### ISSUE TITLE
Handle has wrong size after dataset changed

### ISSUE THREAD

**Issue by cmatsuoka** [plusCubed/recycler-fast-scroll#14]
The fast scroll handle is automatically shown after the adapter is repopulated and the new contents are shown, but the handle size is still based on the previous content size. Only after the first scroll action the handle size is recalculated and shown with correct size.

Also it could be interesting to have an option to not show the fast scroll handle automatically after the dataset is changed.

Original content (handle size is correct):
![image](https://cloud.githubusercontent.com/assets/317355/12377081/57ae4578-bcf7-11e5-896b-efe2b2ebbadb.png)

Dataset changed (handle size is wrong, keeps the same size of original content):
![image](https://cloud.githubusercontent.com/assets/317355/12377085/63f2325e-bcf7-11e5-9017-87acc18a93f6.png)

After scroll (handle size is recalculated):
![image](https://cloud.githubusercontent.com/assets/317355/12377088/73012854-bcf7-11e5-8865-e4b9e5d9b66b.png)

**Comment by pluscubed** [comment]
Fixed in 0.3.1
